who = [
'who are playing sporting events',
'Who is Kyle Squires',
'Who is Morgan Olsen',
'Who were the Hohokam',
'Who is Jeffrey Goss',
'Who is Gordon Wishon',
'Who is Phil Regier',
'Who is Mark Searle',
'Who is the provost',
'Who is Ray Anderson',
'Who is the AD',
'Who is Jim O Brien',
'Who is Paul Jarman',
'Who is Dan Dillon',
'Who is James Rund',
'Who is José Cárdenas',
'Who is Kevin Salcido',
'Who is Bret Hovell',
'Who is Christine Wilkinson',
'Who is Keith Walton',
'Who is Rich Stanley',
'Who is Stefanie Lindquist',
'Who is Mark Jacobs',
'Who is Amy Hillman',
'Who is Steven Tepper',
'Who is David Guston',
'Who is Alfredo Artiles',
'Who is Keith Lindor',
'Who is George Justice',
'Who is Duane Roen',
'Who is Christopher Callahan',
'Who is Douglas Sylvester',
'Who is Patrick Kenney',
'Who is Ferran Garcia Pichel',
'Who is Marlene Tromp',
'Who is Teri Pipe',
'Who is Jonathan Koppell',
'Who is Elizabeth Wentz',
'Who is Christopher Boone',
'Who is Carole Basile',
'Who is Allen Morrison',
'Who is John Rome',
'Who is Colleen Jennings Roggensack',
'Who is Rocky Harris',
'Who is Morgan Reed',
'Who is Octavio Heredia',
'Who are you',
'Who is Sparky',
'Who is Panch',
'Who is Pat Tillman',
'Who was Mary Lou Fulton',
'Who is Ira Fulton',
'Who is Dr. Michael Crow',
'Who is Kyle Squires',
'Who is Morgan Olsen',
'Who were the Hohokam',
'Who is Jeffrey Goss']

what = [
'what sporting events are happening next week',
'What is a master learner',
'What are the top five states for online enrollment',
'What is a Sun Devil',
'What is ASUs nickname',
'What is the Lantern Walk',
'What Year was ASU founded',
'What other mascots has ASU had',
'What famous architect designed Gammage Auditorium',
'What makes ASU great',
'What are ASU colors',
'What was the catch',
'What is the curtain of distraction',
'What is ASU student newspaper',
'What percentage of ASU students are first generation students',
'What is the oldest trophy in NCAA history',
'What is the seating capacity of Sun Devil Stadium',
'What is A Mountain',
'What is Workday',
'What is Peoplesoft',
'What is the current Budget of ASU',
'What percentage of the Budget comes from the State of Arizona',
'What is the next show at Gammage with available seats and how much do they cost',
'What other names has ASU had',
'What influencial leader visited ASU in 1987',
'What is the ASU Charter',
'What ASU facility currently occupies the site of the ASU football stadium that was replaced by Sun Devil Stadium',
'What is CIDSE',
'What is SEMTE',
'What is SBHSE',
'What is ECEE',
'What is TPS',
'What is SEBE',
'What is EPICS',
'What is the academic bowl',
'What is FURI',
'What is ASU doing about sustainability',
'What is GFA',
'What is Skysong',
'What does IOT mean',
'What is Intel',
'What is the New American University'
]